### ISSUE TITLE
Legacy: Cannot edit metadata when collection has special license (CC-BY-NC-SA 4.0) 

### ISSUE THREAD

**Issue by omehes** [openstax/Products.RhaptosCollection#18]
Steps:
1. open a book with license type 'Creative Commons Attribution-NonCommercial-ShareAlike License (CC-BY-NC-SA 4.0) in legacy
examples of books with this license: all Calculus books:
 https://staging.cnx.org/contents/i4nRcikn@3.7:H2TLb2-S@4/Introduction
2. Go to Metadata and try to edit something 
3. click Save
Expected: Changes should be saved
Actual: Error message is shown "Please correct the indicated errors." and nothing is saved. Book can be published but no metadata changes will be saved. 

Investigated with @reedstrm 

See screenshot

![error-NO2.png](https://images.zenhubusercontent.com/5bc8d1f2fe40ab78d94e65fb/1073f165-2c73-4e76-bc44-9af0957ce94b)

**Comment by omehes** [comment]
List of books with special licensing:

```moduleid |                name                | parent |      authors      |   parentauthors   
----------+------------------------------------+--------+-------------------+-------------------
 col24202 | Multiple Integration               | 245909 | {lienert_c}       | {OpenStaxCollege}
 col12053 | Calculus I                         | 157868 | {clabro}          | {OpenStaxCollege}
 col12172 | TC Calculus 1                      | 189638 | {thartman}        | {OpenStaxCollege}
 col12054 | Calculus II                        | 157865 | {clabro}          | {OpenStaxCollege}
 col12052 | Calculus III                       | 157866 | {clabro}          | {OpenStaxCollege}
 col11963 | Calculus                           |        | {OpenStaxCollege} | 
 col25752 | MCC Math210 Calculus 1 Dean        | 533005 | {judydean}        | {OpenStaxCollege}
 col11965 | Calculus Volume 2                  |        | {OpenStaxCollege} | 
 col11966 | Calculus Volume 3                  |        | {OpenStaxCollege} | 
 col25643 | Calculus Volume 3 for Doug Baldwin | 520536 | {DougBaldwin}     | {OpenStaxCollege}
 col25012 | Derived copy of Calculus Volume 1  | 401958 | {hansc}           | {OpenStaxCollege}
 col25479 | Managerial Accounting - DRAFT      |        | {OpenStaxCollege} | 
 col11964 | Calculus Volume 1                  |        | {OpenStaxCollege} | 
 col26303 | Calculus Volume 1 for Doug Baldwin | 601468 | {DougBaldwin}     | {OpenStaxCollege}```

**Comment by brittweinstein** [comment]
@reedstrm please put points on here

**Comment by omehes** [comment]
@brittweinstein 
verified in qa.cnx.org in calculus I and III books
not fixed/present

**Comment by karenc** [comment]
These are all the books on qa.cnx.org with the by-nc-sa 4.0 license:

```
repository=> select moduleid, name from modules where portal_type = 'Collection' and licenseid = (select licenseid from licenses where code = 'by-nc-sa' and version = '4.0') group by moduleid, name order by moduleid;
 
 moduleid |         name
----------+----------------------
 col11963 | Calculus
 col11964 | Calculus Volume 1
 col11965 | Calculus Volume 2
 col11966 | Calculus Volume 3
 col12052 | Calculus III
 col12053 | Calculus I
 col12054 | Calculus II
 col12172 | TC Calculus 1
 col24202 | Multiple Integration
(9 rows)
```

So looks like we tested the right books.  Perhaps the fix didn't make it to qa or the fix didn't work.  I'll check.

**Comment by karenc** [comment]
It turns out the code was merged and tagged as 0.85, but never got uploaded to our dist server so qa.cnx.org didn't have the latest code.

@omehes Could you try deploying to qa.cnx.org again?  Hopefully it'll work after the deploy.

**Comment by omehes** [comment]
Verified on the latest qa.cnx.org on all Calculus volumes
fixed

**Comment by omehes** [comment]
verified on staging.cnx.org on various books with the special license. Fixed

{"date": "2019-03-04 14:30:54 CST",
 "webview": "6fea2e99064f4522c968ac6b4ada6203d9eb9e5d (v0.47.0)",
 "cnx-archive": "4.11.0",
 "cnx-publishing": "0.15.1",
 "oer.exports": "crusty.cronut v0.73.0",
 "press": "8.0.2",
 "cnx-deploy": "v2.38.2"
}
